void setup() {
  pinMode(13,OUTPUT);
  pinMode(12,OUTPUT);
  pinMode(11,OUTPUT);
  pinMode(6,OUTPUT);
  pinMode(5,OUTPUT);
  pinMode(4,OUTPUT);

}

void loop() {
  digitalWrite(13,HIGH);
  digitalWrite(4,HIGH);
  delay(10000);
  digitalWrite(12,HIGH);
  digitalWrite(4,HIGH);
  digitalWrite(13,LOW);
  digitalWrite(4,LOW);
  delay(4000);
  digitalWrite(11,HIGH);
  digitalWrite(4,HIGH);
    digitalWrite(12,LOW);
  digitalWrite(4,LOW);
  digitalWrite(13,LOW);
  digitalWrite(4,LOW);
  delay(2000);
  digitalWrite(11,HIGH);
  digitalWrite(6,HIGH);
   digitalWrite(11,LOW);
  digitalWrite(4,LOW);
    digitalWrite(12,LOW);
  digitalWrite(4,LOW);
  digitalWrite(13,LOW);
  digitalWrite(4,LOW);
  delay(10000);
  digitalWrite(11,HIGH);
  digitalWrite(5,HIGH);
  delay(4000);
  digitalWrite(11,HIGH);
  digitalWrite(4,HIGH);
  digitalWrite(11,LOW);
  digitalWrite(6,LOW);
   digitalWrite(11,LOW);
  digitalWrite(4,LOW);
    digitalWrite(12,LOW);
  digitalWrite(4,LOW);
  digitalWrite(13,LOW);
  digitalWrite(4,LOW);
  delay(2000);
}
